// iconMap.ts
import {
  IconBrandLaravel,
  IconBrandPhp,
  IconBrandVue,
  IconBrandReact,
  IconBrandNextjs,
  IconBrandTailwind,
  IconBrandBootstrap,
  IconBrandHtml5,
  IconBrandCss3,
  IconBrandSass,
  IconBrandMysql,
  IconBrandDocker,
  IconBrandNodejs,
  IconBrandJavascript,
  IconBrandTypescript,
  IconBrandGit,
  IconBrandFigma,
  IconBrandGithub,
  IconBrandVercel,
  IconBrandAws,
  IconDatabase,
  IconCloud
} from '@tabler/icons-react';

export const iconMap: Record<string, React.FC<{ size?: number; color?: string }>> = {
  laravel: IconBrandLaravel,
  php: IconBrandPhp,
  vue: IconBrandVue,
  react: IconBrandReact,
  nextjs: IconBrandNextjs,
  tailwind: IconBrandTailwind,
  bootstrap: IconBrandBootstrap,
  html: IconBrandHtml5,
  css: IconBrandCss3,
  sass: IconBrandSass,
  mysql: IconBrandMysql,
  postgresql: IconDatabase,
  docker: IconBrandDocker,
  node: IconBrandNodejs,
  javascript: IconBrandJavascript,
  typescript: IconBrandTypescript,
  git: IconBrandGit,
  figma: IconBrandFigma,
  vercel: IconBrandVercel,
  aws: IconBrandAws,
  digitalocean: IconCloud,
  github: IconBrandGithub,
};